version: '3'

services:
  backend:
    build: ./backend
    ports:
      - 5000:80
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - './app'
      - '/app/node_modules'
    stdin_open: true
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on: 
      - backend
    command: npm start
